---
- name: Configure Common Packages
  hosts: all
  become: yes
  tasks:
    - name: Install required common packages
      dnf:
        name:
          - bind-utils
          - man
          - man-pages
          - mlocate
          - sysstat
        state: present
