---
- name: Prepare Kubernetes Node
  hosts: prdx-kube101
  become: yes
  tasks:
    - name: Ensure .kube directory exists
      file:
        path: /home/vagrant/.kube
        state: directory
        owner: vagrant
        group: vagrant

    - name: Install kubectl
      shell: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      args:
        creates: /usr/local/bin/kubectl

    - name: Install Kind
      get_url:
        url: "https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64"
        dest: /usr/local/bin/kind
        mode: '0755'