---
- name: Configure MariaDB Database Server
  hosts: prdx-db101
  become: yes
  vars_files:
    - vars/secrets.yml
  tasks:
    - name: Install MariaDB server and Python library
      dnf:
        name: 
          - mariadb-server
          - python3-PyMySQL
        state: present

    - name: Start and enable MariaDB
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Allow MariaDB through Firewall
      firewalld:
        service: mysql
        permanent: yes
        state: enabled
        immediate: yes

    - name: Create project database
      mysql_db:
        name: ziyoteks_db
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock

    - name: Create database user for Webservers
      mysql_user:
        name: db_user
        password: "{{ db_app_password }}"
        priv: 'ziyoteks_db.*:ALL'
        host: '%'
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock

    - name: Create sample table
      mysql_query:
        login_db: ziyoteks_db
        login_unix_socket: /var/lib/mysql/mysql.sock
        query: |
          CREATE TABLE IF NO          CREATE TABLE IF NO          CREATE TABLE IEN       RY K          CR    name VARCHAR(50),
            state VARCHAR(50)
          )

    - name: Insert sample data
      mysql_query:
        login_db: ziyoteks_db
        login_unix_socket: /var/lib/mysql/mysql.sock
                                      RE INTO classmates (id, n                              (1, 'Wais', 'Vir                   (2,           Istanbul'),
          (3, 'Sacramento', 'California')
