---
- name: Install Nagios NRPE Agents - Final Clean
  hosts: all:!prdx-nagios101:!prdx-ansible101
  become: yes
  tasks:
    - name: Ensure EPEL is present
      package:
        name: epel-release
        state: present

    - name: Install NRPE and Essential Plugins (Manual List)
      package:
        name:
          - nrpe
          - nagios-plugins-load   # For CPU
          - nagios-plugins-disk   # For Disk
          - nagios-plugins-procs  # For Process monitoring
          - nagios-plugins-users  # For User monitoring
          - nagios-plugins-swap   # For RAM/Swap
          - nagios-plugins-http   # Required for Webservers
          - nagios-plugins-dns    # Required for prdx-dns101
        state: present

    - name: Configure NRPE allowed hosts
      lineinfile:
        path: /etc/nagios/nrpe.cfg
        regexp: '^allowed_hosts='
        line: 'allowed_hosts=127.0.0.1,::1,192.168.56.40'

    - name: Ensure Firewall is running and Port 5666 is open
      block:
        - name: Start Firewalld
          service:
            name: firewalld
            state: started
            enabled: yes
        - name: Open Port 5666
          firewalld:
            port: 5666/tcp
            permanent: yes
            state: enabled
            immediate: yes
      ignore_errors: yes

    - name: Restart and Enable NRPE
      service:
        name: nrpe
        state: restarted
        enabled: yes