---
- name: Deploy Docker Web Application
  hosts: prdx-dprimary101
  become: yes
  vars:
    app_url: "https://aws-tc-largeobjects.s3-us-west-2.amazonaws.com/CUR-TF-200-ACACAD/studentdownload/lab-app.tgz"
    docker_dir: "/vagrant/ansible/docker"

  tasks:
    - name: Ensure Docker repo is added
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: Install Docker and required packages
      dnf:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - python3-pip
        state: present

    - name: Install Correct Docker SDK and Requests version
      pip:
        name: 
          - docker==6.1.3
          - requests==2.31.0
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Ensure lab-app directory exists
      file:
        path: "{{ docker_dir }}/lab-app"
        state: directory
        mode: '0755'

    - name: Download and extract lab-app from S3
      unarchive:
        src: "{{ app_url }}"
        dest: "{{ docker_dir }}/lab-app/"
        remote_src: yes
        extra_opts:
          - '--no-same-owner'
          - '--no-same-permissions'
        mode: '0755'

    - name: Build Docker Image
      community.docker.docker_image:
        name: lab-app
        build:
          path: "{{ docker_dir }}"
        source: build
        docker_host: unix://var/run/docker.sock
        state: present

    - name: Run Docker Container
      community.docker.docker_container:
        name: web-app
        image: lab-app
        state: started
        restart_policy: always
        network_mode: host
        docker_host: unix://var/run/docker.sock