---
- name: Prepare All Nodes with Common Configuration
  hosts: all
  become: yes
  tasks:
    - name: Install common packages
      yum:
        name:
          - curl
          - git
          - wget
          - net-tools
          - epel-release
        state: present
      # This skips the task ONLY for the controller to save memory
      when: inventory_hostname != 'prdx-ansible101'
      ignore_errors: yes

    - name: Ensure SSH directory exists for vagrant user
      file:
        path: /home/vagrant/.ssh
        state: directory
        mode: '0700'
        owner: vagrant
        group: vagrant

    - name: Disable SELinux (common for Lab environments)
      selinux:
        state: disabled

    - name: Ensure SELinux is disabled in config file
      lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX=disabled'