---
- name: Configure HAProxy Load Balancer
  hosts: prdx-haproxy101
  become: yes
  tasks:
    - name: Install HAProxy
      package:
        name: haproxy
        state: present

    - name: Configure HAProxy Config
      copy:
        dest: /etc/haproxy/haproxy.cfg
        content: |
          global
              user haproxy
              group haproxy
              daemon
          defaults
              mode http
              timeout connect 5000ms
              timeout client 50000ms
              timeout server 50000ms
          frontend http-in
              bind *:80
              default_backend web-backend
          backend web-backend
              balance roundrobin
              server s1 192.168.56.21:80 check
              server s2 192.168.56.22:80 check
              server s3 192.168.56.23:80 check

    # WE REMOVED THE FIREWALL TASK ENTIRELY HERE
    
    - name: Ensure HAProxy is restarted
      service:
        name: haproxy
        state: restarted
        enabled: yes
